var s =
{
    "yy9juae1njxg8pvi": {
        "icon":"",
        "type":"carriageway",
        "tag":"",
        "cycleTime":100,
        "avgIntensity":900,
        "capacity":1800,
        "routeTime":20,
        "length":300,
        "dispersion":0.5,
        "id":"yy9juae1njxg8pvi",
        "edges":[
            {
                "target":"yy9juae1njxg8pvi",
                "portion":900,
                "source":"go6sdm9j17tlnmi",
                "id":"ele0"
            }
        ]
    },
    "wnfpbyhb599q9f6r": {
        "icon":"",
        "type":"crossRoad",
        "name":"",
        "cycleTime":100,
        "offset":10,
        "phases": [
            {
                "tag":"ph-1",
                "length":50,
                "minLength":15

            },
            {
                "tag":"ph-2",
                "length":50,
                "minLength":15
            }
        ],
        "id":"wnfpbyhb599q9f6r",
        "edges":[]
    },
    "go6sdm9j17tlnmi":{
        "icon":"Q",
        "type":"stopline",
        "tag":"",
        "color":"primary",
        "cycleTime":100,
        "avgIntensity":900,
        "capacity":1800,
        "greenOffset1":0,
        "greenOffset2":0,
        "intervals": [[0,20],[40,55]],
        "greenPhases": [false,true],
        "id":"go6sdm9j17tlnmi",
        "parent":"wnfpbyhb599q9f6r",
        "edges":[]
    },
    "pzxfd24chljl9pb9":{
        "icon":"",
        "type":"crossRoad",
        "name":"",
        "cycleTime":100,
        "offset":61,
        "phases":[
            {
                "tag":"ph-1",
                "length":30,
                "minLength":15
            },
            {
                "tag":"ph-2",
                "length":30,
                "minLength":15
            },
            {
                "tag":"ph-3",
                "length":40,
                "minLength":15
            }
        ],
        "id":"pzxfd24chljl9pb9",
        "edges":[]
    },
    "1x40nxubh91nstt9":{
        "icon":"Q",
        "type":"stopline",
        "tag":"",
        "color":"primary",
        "cycleTime":100,
        "avgIntensity":900,
        "capacity":1800,
        "greenOffset1":0,
        "greenOffset2":0,
        "intervals": [[0,20],[40,55]],
        "greenPhases":[true,true,false],
        "id":"1x40nxubh91nstt9",
        "parent":"pzxfd24chljl9pb9",
        "edges":[
            {
                "target":"1x40nxubh91nstt9",
                "portion":900,
                "source":"yy9juae1njxg8pvi",
                "id":"ele1"
            }
        ]
    },
    "hks3ia83cg9o1or":{
        "icon":"Q",
        "type":"stopline",
        "tag":"",
        "color":"primary",
        "cycleTime":100,
        "avgIntensity":900,
        "capacity":1800,
        "greenOffset1":0,
        "greenOffset2":0,
        "intervals":[[0,20],[40,55]],
        "greenPhases":[true,false],
        "id":"hks3ia83cg9o1or",
        "edges":[
            {
                "source":"1x40nxubh91nstt9",
                "target":"hks3ia83cg9o1or",
                "portion":900,
                "id":"ele2"
            }
        ]
    }
};